In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# loading all dataset
df=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\dataset.csv')
desc=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\symptom_Description.csv')
precaution=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\symptom_precaution.csv')
severity=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\Symptom-severity.csv')

### main dataset

In [16]:
print("main dataset shape:",df.shape)
print("\nColumns:",df.columns.tolist())
print("\n first few rows")
df.sample(5)

main dataset shape: (4920, 18)

Columns: ['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14', 'Symptom_15', 'Symptom_16', 'Symptom_17']

 first few rows

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
969,Jaundice,itching,vomiting,fatigue,weight_loss,high_fever,yellowish_skin,dark_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2956,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition,spotting_ urination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4048,Varicose veins,fatigue,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels,prominent_veins_on_calf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4078,hepatitis A,joint_pain,vomiting,yellowish_skin,dark_urine,nausea,loss_of_appetite,abdominal_pain,diarrhoea,mild_fever,yellowing_of_eyes,muscle_pain,NaN,NaN,NaN,NaN,NaN,NaN
2704,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# how many unique diseases
print("\n Unique diseases:", df['Disease'].nunique())
df['Disease'].value_counts()

 Unique diseases: 41

Disease
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [21]:
#how many unique symptoms
symptom_cols=[col for col in df.columns if col.startswith('Symptom_')]
print("\n Sympton cols:",len(symptom_cols))

all_symptoms=set()
for col in symptom_cols:
    all_symptoms.update(df[col].dropna().unique())
print("\n unique symptoms:", len(all_symptoms))

 Sympton cols: 17

 unique symptoms: 131

## other datasets

In [26]:
print("\n Secerity dataset:")
print("\nshape:",severity.shape)
print("Symptoms with severity:", len(severity))
severity.sample(5)

 Secerity dataset:

shape: (133, 2)
Symptoms with severity: 133

                     Symptom  weight
90        foul_smell_ofurine       5
86              unsteadiness       4
73       swollen_extremeties       5
6                 joint_pain       3
91  continuous_feel_of_urine       6

In [30]:
print("\n Description datset:")
print("\n shape:", desc.shape)
desc.sample(5)

 Description datset:

 shape: (41, 2)

                Disease                                        Description
38            Arthritis  Arthritis is the swelling and tenderness of on...
33          Hepatitis E  A rare form of liver inflammation caused by in...
15  Peptic ulcer diseae  Peptic ulcer disease (PUD) is a break in the i...
30     Bronchial Asthma  Bronchial asthma is a medical condition which ...
18          Chicken pox  Chickenpox is a highly contagious disease caus...

In [28]:
print("Precaution dataset:")
print("\n Shape:",precaution.shape)
precaution.sample(5)

Precaution dataset:

 Shape: (41, 5)

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
9,(vertigo) Paroymsal Positional Vertigo,lie down,avoid sudden change in body,avoid abrupt head movment,relax
36,Heart attack,call ambulance,chew or swallow asprin,keep calm,NaN
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
39,Gastroenteritis,stop eating solid food for while,try taking small sips of water,rest,ease back into eating
33,Hepatitis E,stop alcohol consumption,rest,consult doctor,medication